[build]
publish = "public"
command = "hugo"

[build.environment]
NODE_VERSION = "24"

[image]
name = "ubuntu-noble"

[context.production.environment]
HUGO_VERSION = "0.155.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.155.1"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.155.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
from = "/"
to = "/posts/"
status = 302